name: New Integration Request
description: An idea for any product/specification/workflow you use that you'd like Postman to integrate with. 
title: "New Integration Request - <product name>"
labels: "feature,product/integrations"
assignees: "abhijitkane"
body:
- type: textarea
  attributes:
    label: Describe your current workflow
    description: |
      How do you use Postman with the rest of the tools in your stack to achieve your use-case?
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your ideal workflow
    description: |
      How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: |
      A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: | 
      Add any other context or screenshots about the feature request here.
  validations:
    required: false
